apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-vote-api
  name: pipelines-vote-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines-vote-api
  template:
    metadata:
      labels:
        app: pipelines-vote-api
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/devsecops/pipelines-vote-api-26-1
        ## Start: Secret in environment are not best practice 
          env:
          - name: PASSWORD
            value: "password"        
          - name: DB_SECRET
            value: "password"                    
        ## End : Secret in environment are not best practice 
          imagePullPolicy: Always
          name: pipelines-vote-api
          ports:
            - containerPort: 9000
              protocol: TCP
        ## Start: Pod running as privileged not best practice 
          securityContext:
            privileged: true              
        ## End: Pod running as privileged not best practice
